#!/bin/bash

echo "🗄️  DATABASE QUICK ACCESS CARD"
echo "═══════════════════════════════════════════════"
echo ""
echo "📍 Provider: Neon"
echo "🌐 Dashboard: https://console.neon.tech"
echo ""
echo "🔑 Connection String Locations:"
echo "   • Local:      .env.local"
echo "   • Vercel:     https://vercel.com/dashboard → Settings → Env Vars"
echo "   • GitHub:     https://github.com/cubingkeralaorg/cubingkerala/settings/secrets"
echo "   • Neon:       https://console.neon.tech → Project → Connection Details"
echo ""
echo "🛠️  Quick Actions:"
echo "   • View data:        npx prisma studio"
echo "   • Backup:           pg_dump \"\$DATABASE_URL\" > backup.sql"
echo "   • Migrations:       npx prisma migrate dev"
echo "   • Push schema:      npx prisma db push"
echo ""
echo "📊 Current Database:"
cat .env.local 2>/dev/null | grep DATABASE_URL | sed 's/:[^:@]*@/:****@/' || echo "   ⚠️  .env.local not found"
echo ""
